### ISSUE TITLE
Return value as UTC offset?

### ISSUE THREAD

**Issue by apiszcz** [MrMinimal64/timezonefinder#106]
Please consider a return option as the UTC offset +0300, etc. 

`datetime.datetime.now(pytz.timezone('Asia/Jerusalem')).strftime('%z')`

Thank you.

**Comment by MrMinimal64** [comment]
Thanks for this suggestion.
I am aware that many users of this package want to achieve something comparable.
Due to the following reasons I still do not consider this functionality worth including:

- the functionality is covered by other packages (`datetime`, `pytz`)
- the functionality is fairly simple
- the functionality is not general as there are many similar use cases which would need separate implementations 
- the functionality is closely connected to `datetimes` and hence does not lie within the actual scope of this package
