### ISSUE TITLE
Daylight saving information

### ISSUE THREAD

**Issue by pramodhrachuri** [MrMinimal64/timezonefinder#108]
Hi,
I expected that by giving a timestamp, the method should be able to give different timezones depending on daylight savings. But by the parameters to the methods, I see that there is no way I can find if the location is following daylight time or not at a particular time. Is that correct?

**Comment by MrMinimal64** [comment]
Hello, 
the purpose of this package is solely to determine the timezone given a coordinate pair. 
Timezones are on their own independent from daylight saving times.
Just in combination with an actual datetime a daylight saving time can be determined.
In order to solve your problem, please have a look here: http://pytz.sourceforge.net/
Hope that could help.
