### ISSUE TITLE
Pin setup.py install_requires versions

### ISSUE THREAD

**Issue by BrianBunker** [MrMinimal64/timezonefinder#73]
First, thanks for `timezonefinder`!

I'm using the PyPI v3.2.0 of `timezonefinder` which has a setup requirement of `numpy`. The pinned requirements.txt for version v3.2.0 is `numpy==1.15.3`. On 2019/01/13 v1.16.0 of `numpy` was released. Since the version was not pinned in setup.py to 1.15.3, my project was automatically updated to `numpy` 1.16.0, which broke the application.

Please consider pinning install_requires package versions so `timezonefinder` doesn't inadvertently automatically upgrade dependencies to the latest version.

**Comment by MrMinimal64** [comment]
Thanks for reporting this. I will include this in the next release.

**Comment by adamchainz** [comment]
Library level version pinning is actually rarely done in the Python community, instead relying on applications pinning their requirements. Large backwards incompatibilities are rare (cf Django, which has 4 requirements in its setup.py, and the only pinning is for minimum version https://github.com/django/django/blob/master/setup.py#L86 ). You can also pin *ranges* of requirements, e.g. `numpy<1.16.0`, since at least patch versions should be well tested.

@BrianBunker you will be best served by managing your application's requirements with pinning. I highly recommend https://github.com/jazzband/pip-tools as a way of getting started, writing a `requirements.in` and "compiling" it to a `requirements.txt` for your project. https://github.com/pypa/pipenv is a more futuristic, advanced tool for this.

**Comment by MrMinimal64** [comment]
@BrianBunker, can you please post the error that is causing the numpy import to fail. Maybe there is an easy fix for supporting the latest numpy release (instead of pinning its version).

**Comment by BrianBunker** [comment]
@MrMinimal64 and @adamchainz Thanks for the fast responses and patience. I'll close this for now as it's not an issue with timezonefinder.

Again, thanks for the library.
