### ISSUE TITLE
add option to only use shortcuts

### ISSUE THREAD

**Issue by MrMinimal64** [MrMinimal64/timezonefinder#87]
as suggested by @zedrdave in #85:

- add an option to only use shortcuts (like with timezonefinderL, new function "shortcut_timezone_at()"?)
- make the remaining binary files optional (new child class which loads only shortcuts binary?)
- describe how the binary files can be deleted to free up disk space

-> both of two worlds, make timezonefinderL superfluous (no more maintainance)

**Comment by zedrdave** [comment]
This is mostly a personal choice, but I think I would go for an `__init__` param, over a child class, to restrict the files that are loaded.
Even better: why not simply check for the files' presence? (and perhaps still have a flag to allow `in_memory` to be restricted to shortcuts only, regardless of polygon files' presence)

Regarding binary files: one option would also be to have the setup script download the original files and compiles them on the fly. There must then be a way to provide setup.py options (but I have never tried). I already made my own bash script to download and recompile files on the fly (since I needed ocean tz and did not want to include large recompiled binaries into the repository).

**Comment by zedrdave** [comment]
Regarding the first point (and in line with my previous comment), I think you would minimise code replication (and therefore maintenance effort and risk of bug) by adding more flag parameters to a single lookup function.

You could even abstract the process a bit, to make it simpler to understand to users: instead of having to understand what 'shortcuts' etc. stand for, flags would be `alwaysReturn`, `highPrecision` etc.

Thanks a lot for all the hard work you already put into this, and for your reactivity on these suggestions!

**Comment by MrMinimal64** [comment]
future releases of timezonefinder will only contain the data of the shortcuts (like current timezonefinderL), cf. #89 
the code will check what is "installed" and react accordingly.
work in progress.

**Comment by MrMinimal64** [comment]
> I already made my own bash script to download and recompile files on the fly

@zedrdave Could you please provide this?

**Comment by zedrdave** [comment]
@MrMinimal64 With pleasure… Though I don't think there is anything particularly groundbreaking to it:

```
#!/usr/bin/env zsh

# Abort if any command fails:
set -e

# get and install timezonefinder
git clone https://github.com/MrMinimal64/timezonefinder.git
cd timezonefinder
pipenv install -r requirements.txt

# Download latest data
wget https://github.com/evansiroky/timezone-boundary-builder/releases/latest/download/timezones-with-oceans.geojson.zip
unzip timezones-with-oceans.geojson.zip
mv dist/combined-with-oceans.json combined.json
pipenv run python -m timezonefinder.file_converter
```

(it also assumes a number of utilities are installed: git, pipenv, unzip…)

**Comment by MrMinimal64** [comment]
Since [v4.4.0 ](https://github.com/MrMinimal64/timezonefinder/releases/tag/v4.4.0) the class ``TimezoneFinderL`` allows only using shortcuts. The binary files can be deleted if necessary (cf. [documentation](https://timezonefinder.readthedocs.io/en/latest/1_usage.html#timezonefinderl)).

Let me know if this functionality is not enough for your usecase.
